/* M1 self-quiz · ungraded · 8 items (W8 uses 0–3, W9 uses 4–7) */
window.DL_QUIZ=[
{q:"读本对“学习”的定义中，学习一定发生在哪里？Where, according to the reader, does learning always happen?",options:["在学校 At school","在大脑中 In the brain","在课堂上 In the classroom","在书本里 In books"],a:1,why:"学习可能发生在学校、家里或任何地方，但一定 100% 发生在大脑中（All learning is brain learning）。Learning may happen anywhere; it always happens in the brain."},
{q:"马克·吐温说“我从来不会因为上学而影响我受教育”，他想提醒我们什么？What is Twain's point?",options:["上学没有用 School is useless","上学和学习是两码事 Schooling and learning are different things","只有自学才是学习 Only self-study counts","学历越高越好 Higher degrees are better"],a:1,why:"完成“上学”这个动作，不等于自然而然地学到了东西。Completing the act of schooling does not automatically produce learning."},
{q:"读本说把守学习大门的“两个门卫”是什么？Which two “gatekeepers” guard the door to learning?",options:["老师和家长 Teachers and parents","时间和金钱 Time and money","情绪和动机 Emotion and motivation","天赋和运气 Talent and luck"],a:2,why:"情绪不对、动机不足，人就“身体在教室、大脑在门外”。With the wrong emotion or too little motivation, the body sits in class while the brain stays outside."},
{q:"下面哪种做法研究显示学习效果最好？Which practice does research rate most effective?",options:["把课文重读三遍 Rereading three times","用荧光笔划重点 Highlighting","合上书把内容复述出来 Closing the book and recalling from memory","考前一晚集中复习 Cramming the night before"],a:2,why:"提取练习（自己回忆）比重读、划线、临时突击有效得多。Retrieval practice beats rereading, highlighting and cramming by a wide margin."},
{q:"读本第 03 章里，作者从“差生”变好的转机首先发生在哪里？Where did the author's turnaround begin (Ch. 03)?",options:["一次考试 An exam","一次跳绳比赛 A skipping-rope contest","换了老师 A new teacher","补习班 A tutoring class"],a:1,why:"观察→尝试→休息再试→成功→被认可，这个循环让他重新认识了自己。Observe → try → rest and retry → succeed → be recognised: that loop changed how he saw himself."},
{q:"第 04 章区分了外部动机与内部动机。下面哪个是内部动机？Which is an example of internal motivation (Ch. 04)?",options:["为了得到老师表扬而练习 Practising to be praised","没有人表扬也因为吹得好而高兴，继续练 Practising because playing well feels good, praise or not","为了奖金学习 Studying for a bonus","为了不被批评而写作业 Doing homework to avoid criticism"],a:1,why:"内部动机来自自我奖赏，不依赖外部的奖励。Internal motivation is self-rewarding and does not depend on outside rewards."},
{q:"讲“成功学习经历”时，量规要求把成功归因于什么？What must the learning story attribute success to?",options:["运气 Luck","天赋 Talent","具体的方法或条件 Specific methods or conditions","老师的水平 The teacher's skill"],a:2,why:"“我努力了”“我聪明”都太笼统；要说出你具体做了什么、在什么条件下。“I worked hard” or “I'm smart” is too vague — name what you did and under what conditions."},
{q:"“我的学习观”短文的一个硬性要求是什么？One hard requirement of the mini-essay is:",options:["至少 1000 字 At least 1000 words","引用读本中至少两个概念 Cite at least two reader concepts","必须用英文写 Must be in English","必须用 AI 润色 Must be polished by AI"],a:1,why:"300–500 字，中文或英文皆可，引用读本至少两个概念并和自己的观点连起来。300–500 words in either language; cite at least two reader concepts and connect them to your own view."}
];
